# Generated by Django 2.2.3 on 2019-09-17 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sell',
            name='bookImage',
            field=models.ImageField(blank=True, default='images/noBook.png', null=True, upload_to='images/'),
        ),
    ]
