# Generated by Django 2.2.4 on 2019-09-19 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20190917_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='phoneNo',
            field=models.CharField(default=9075673327, max_length=10),
            preserve_default=False,
        ),
    ]
