# Generated by Django 2.2.3 on 2019-09-19 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_userprofileinfo_phoneno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='phoneNo',
            field=models.CharField(default='9075673327', max_length=10),
        ),
    ]
