# Generated by Django 2.2.3 on 2019-09-19 18:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0004_auto_20190919_2117'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notify',
            fields=[
                ('notify_id', models.AutoField(primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('add_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addNotify', to='user.Sell')),
                ('buyer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyerNotify', to=settings.AUTH_USER_MODEL)),
                ('seller_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sellerNotify', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
