# Generated by Django 2.2.3 on 2019-10-22 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20191007_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sell',
            name='description',
            field=models.CharField(max_length=500),
        ),
    ]
